# Generated by Django 2.2 on 2019-04-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190417_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dalabtest',
        ),
    ]
