# Generated by Django 2.2 on 2019-04-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dalabtest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dalabtest',
            table='uniondaily',
        ),
    ]
