# Generated by Django 2.2 on 2019-04-18 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaumBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, null=True)),
                ('search_keyword', models.CharField(max_length=30, null=True)),
                ('origin_keyword', models.CharField(max_length=30, null=True)),
                ('item_type', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('content', models.TextField(null=True)),
                ('no_likes', models.IntegerField(default=0, null=True)),
                ('no_images', models.IntegerField(default=0, null=True)),
                ('no_comments', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NaverBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, null=True)),
                ('search_keyword', models.CharField(max_length=30, null=True)),
                ('origin_keyword', models.CharField(max_length=30, null=True)),
                ('item_type', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('content', models.TextField(null=True)),
                ('no_likes', models.IntegerField(default=0, null=True)),
                ('no_images', models.IntegerField(default=0, null=True)),
                ('no_comments', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NaverNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, null=True)),
                ('search_keyword', models.CharField(max_length=30, null=True)),
                ('origin_keyword', models.CharField(max_length=30, null=True)),
                ('item_type', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('original_link', models.TextField(null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('content', models.TextField(null=True)),
                ('no_emotions', models.IntegerField(default=0, null=True)),
                ('no_e_likes', models.IntegerField(default=0, null=True)),
                ('no_e_warms', models.IntegerField(default=0, null=True)),
                ('no_e_sads', models.IntegerField(default=0, null=True)),
                ('no_e_angries', models.IntegerField(default=0, null=True)),
                ('no_e_wants', models.IntegerField(default=0, null=True)),
                ('no_images', models.IntegerField(default=0, null=True)),
                ('no_comments', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, null=True)),
                ('search_keyword', models.CharField(max_length=30, null=True)),
                ('origin_keyword', models.CharField(max_length=30, null=True)),
                ('item_type', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('url', models.TextField(null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('twitter_id', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('no_replies', models.IntegerField(blank=True, null=True)),
                ('no_favorites', models.IntegerField(blank=True, null=True)),
                ('no_retweets', models.IntegerField(blank=True, null=True)),
                ('hash_tag', models.TextField(null=True)),
                ('mention', models.TextField(null=True)),
                ('geo_location', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
