# Generated by Django 2.2 on 2019-06-03 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, null=True)),
                ('search_keyword', models.CharField(max_length=30, null=True)),
                ('channel', models.CharField(max_length=100, null=True)),
                ('channel_sub', models.CharField(max_length=100, null=True)),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('content_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MyCollectionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comments', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_images', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_likes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_replies', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_favorites', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_retweets', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_emotions', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_e_likes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_e_warms', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_e_sads', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_e_angries', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_e_wants', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iCrawler.MyCollection')),
            ],
        ),
    ]
