# Generated by Django 2.2 on 2019-06-12 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0004_auto_20190612_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycollectionstats',
            name='channel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycollectionstats',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mycollectionstats',
            name='search_keyword',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mycollection',
            name='search_keyword',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
