# Generated by Django 2.2 on 2019-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0006_mycollection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycollection',
            name='job_ids',
            field=models.TextField(null=True),
        ),
    ]
