# Generated by Django 2.2 on 2019-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0007_mycollection_job_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycollection',
            name='job_ids',
        ),
        migrations.AddField(
            model_name='mycollection',
            name='jobids',
            field=models.TextField(null=True),
        ),
    ]
