# Generated by Django 2.2 on 2019-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0008_auto_20190619_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='jobids',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
