# Generated by Django 2.2 on 2019-06-20 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0009_auto_20190619_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.MyCollection')),
                ('daum_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.DaumBlog')),
                ('naver_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.NaverBlog')),
                ('naver_news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.NaverNews')),
                ('twitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.Twitter')),
            ],
        ),
    ]
