# Generated by Django 2.2 on 2019-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0010_mycollectiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverblog',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
