# Generated by Django 2.2 on 2019-06-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0011_auto_20190620_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100, null=True)),
                ('middle_category', models.CharField(max_length=100, null=True)),
                ('search_word', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iCrawler.MyKeyword')),
            ],
        ),
    ]
