# Generated by Django 2.2 on 2019-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCrawler', '0012_mykeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykeyword',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
