# Generated by Django 2.2 on 2019-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendWithItemFreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('channel', models.CharField(max_length=100, null=True)),
                ('sub_channel', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('sub_category', models.CharField(max_length=100, null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('item_freq', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'mediaItemFrequency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendWithSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('panel_purchase_amount_ave', models.FloatField(null=True)),
                ('panel_purchase_amount_sum', models.FloatField(null=True)),
                ('retail_price', models.FloatField(null=True)),
                ('wholesale_price', models.FloatField(null=True)),
                ('news_freq', models.IntegerField(null=True)),
                ('video_freq', models.IntegerField(null=True)),
                ('blog_freq', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'new_collection1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Twitter2010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
