# Generated by Django 2.2.1 on 2019-06-04 09:15

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_keyword', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Content', models.CharField(max_length=10000, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'onion2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_keyword', models.CharField(max_length=100, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('cdate', models.DateTimeField(null=True)),
                ('total_date', models.CharField(max_length=100, null=True)),
                ('the_json', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(default=dict), size=None)),
            ],
            options={
                'db_table': 'practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='publish_onion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_keyword', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Content', models.CharField(max_length=10000, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('cdate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'published_onion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='topic_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_keyword', models.CharField(max_length=100, null=True)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('cdate', models.DateTimeField(null=True)),
                ('total_date', models.CharField(max_length=100, null=True)),
                ('keyword_list', models.CharField(max_length=200, null=True)),
                ('count_list', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'topic_result',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='trendwithsales',
            table='new_collection2',
        ),
    ]
